#!/bin/bash
# Have tagboy find images from about the same position

# Usage: tb-gpspos [options] --imatch '*.jpg' dir

# This is crude.  We just use the human printed position (which is
# deg, minutes, seconds) and strip off any decimal portion.
# From: http://www.zodiacal.com/tools/lat_table.php
# At the Equator:
# One second of latitude =   30.72 m  or 100.77 ft
# One second of longitude =  30.92 m  or 101.45 ft
# At latitude 40deg:
# One second of latitude =   30.84 m  or 101.19 ft
# One second of longitude =  23.72 m  or  77.82 ft

abort() {
  echo "$@"
  exit
}

# This is the python code that tagboy.py will run
# We use bash strings to make the formatting easy to see.
begin='\
import re
global pos, subst_re
pos={}
subst_re=re.compile("\\.\d+")
print "Looking for files at similar GPS locations..."
'
# A dictionary of dictionaries makes searching fast
# pos["lat, lon"] -> (filepath...)

each='\
import re
global pos, subst_re

try:
  lat = objs["Exif.GPSInfo.GPSLatitude"].human_value.strip()
  lon = objs["Exif.GPSInfo.GPSLongitude"].human_value.strip()
  lat2 = re.sub(subst_re, "", lat)
  lon2 = re.sub(subst_re, "", lon)
  if not ("0/0" in lat):
    #print "lat: %s -> %s; \tlon: %s -> %s" % (lat, lat2, lon, lon2)
    kk = "%s, %s" % (lat2, lon2)
    if not (kk in pos):
      pos[kk] = list()
    pos[kk].append(filepath)
  else:
    skip = 1
except KeyError:
  skip = 1
'

end='\
global pos
print "Found %d out of %d files." % (matchcount, filecount)
print "Here are files at the same integer second (~50-100ft):"
for kk in sorted(pos.keys()):
  print "@@ %s:\n%s" % (kk, "\n".join(pos[kk]))
'

tagboy --begin "$begin" --eval "$each" --end "$end" --long "$@"
