#!/bin/bash
# Have tagboy generate a count of non-empty tags (by name)

# Usage: tb-tagcount [options] --imatch '*.jpg' dirs...

abort() {
  echo "$@"
  exit
}

# This is the python code that tagboy.py will run
# We use bash strings to make the formatting easy to see.
begin='\
global hist
hist={}
'

# We count only long names with non-empty values
each='\
global hist
tkeys = selected.keys() if selected else tags.keys()
for kk in tkeys:
  if not tags[kk] or kk.find(".") < 1:
    continue
  if hist.has_key(kk):
    hist[kk] += 1
  else:
    hist[kk] = 1
'

end='\
global hist
for kk in sorted(hist.keys()):
  print "%60s: %d" % (kk, hist[kk])
print "Looked at %d files" % filecount
'

tagboy --begin "$begin" --eval "$each" --end "$end" "$@"
